package com.kairowan.generator.core

import java.io.File

/**
 * 代码生成器 - 模板生成
 * 根据表结构自动生成 Entity, Service, Controller 代码
 * 
 * @author Kairowan
 * @date 2026-01-18
 */
class CodeGenerator(
    private val basePackage: String = "com.kairowan",
    private val outputDir: String = "src/main/kotlin"
) {

    /**
     * 生成所有代码文件
     */
    fun generateAll(tableName: String, columns: List<ColumnInfo>, primaryKey: String): GeneratedCode {
        val className = toClassName(tableName)
        
        return GeneratedCode(
            entityCode = generateEntity(tableName, className, columns, primaryKey),
            serviceCode = generateService(className),
            controllerCode = generateController(tableName, className, primaryKey),
            className = className,
            tableName = tableName
        )
    }

    /**
     * 生成 Entity 代码
     */
    fun generateEntity(tableName: String, className: String, columns: List<ColumnInfo>, primaryKey: String): String {
        val entityPackage = "$basePackage.framework.web.domain"
        
        val imports = mutableSetOf<String>()
        imports.add("org.ktorm.schema.Table")
        imports.add("org.ktorm.entity.Entity")
        
        // 动态添加导入
        columns.forEach { col ->
            when (col.toKotlinType().replace("?", "")) {
                "LocalDateTime" -> imports.add("java.time.LocalDateTime")
                "LocalDate" -> imports.add("java.time.LocalDate")
                "BigDecimal" -> imports.add("java.math.BigDecimal")
            }
            imports.add("org.ktorm.schema.${col.toKtormType()}")
        }
        
        val importLines = imports.sorted().joinToString("\n") { "import $it" }
        
        val properties = columns.joinToString("\n    ") { col ->
            val propName = col.toPropertyName()
            val propType = col.toKotlinType()
            "var $propName: $propType"
        }
        
        val tableColumns = columns.joinToString("\n    ") { col ->
            val propName = col.toPropertyName()
            val ktormType = col.toKtormType()
            val isPk = col.columnName.equals(primaryKey, ignoreCase = true)
            
            if (isPk) {
                "val $propName = $ktormType(\"${col.columnName}\").primaryKey().bindTo { it.$propName }"
            } else {
                "val $propName = $ktormType(\"${col.columnName}\").bindTo { it.$propName }"
            }
        }
        
        return """
package $entityPackage

$importLines

/**
 * $className 实体
 * Generated by CodeGenerator
 */
interface $className : Entity<$className> {
    companion object : Entity.Factory<$className>()
    
    $properties
}

object ${className}s : Table<$className>("$tableName") {
    $tableColumns
}
""".trimIndent()
    }

    /**
     * 生成 Service 代码
     */
    fun generateService(className: String): String {
        val servicePackage = "$basePackage.framework.web.service"
        val domainPackage = "$basePackage.framework.web.domain"
        
        return """
package $servicePackage

import $domainPackage.$className
import $domainPackage.${className}s
import org.ktorm.database.Database

/**
 * ${className}Service
 * Generated by CodeGenerator
 */
class ${className}Service(database: Database) : KService<$className>(database, ${className}s)
""".trimIndent()
    }

    /**
     * 生成 Controller 代码
     */
    fun generateController(tableName: String, className: String, primaryKey: String): String {
        val controllerPackage = "$basePackage.framework.web.controller"
        val servicePackage = "$basePackage.framework.web.service"
        val domainPackage = "$basePackage.framework.web.domain"
        
        val routePath = tableName.replace("_", "/").replace("sys/", "system/")
        val pkProp = primaryKey.split("_")
            .mapIndexed { index, s -> 
                if (index == 0) s.lowercase() 
                else s.lowercase().replaceFirstChar { it.uppercase() }
            }
            .joinToString("")
        
        return """
package $controllerPackage

import com.kairowan.common.KResult
import $domainPackage.$className
import $servicePackage.${className}Service
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import org.koin.ktor.ext.inject
import io.github.smiley4.ktorswaggerui.dsl.*

/**
 * ${className}Controller
 * Generated by CodeGenerator
 */
class ${className}Controller : KController() {

    fun Route.routes() {
        val service by inject<${className}Service>()

        route("/$routePath") {
            // 列表查询
            get("/list", {
                tags = listOf("$className")
                summary = "获取${className}列表"
                securitySchemeName = "BearerAuth"
            }) {
                val page = getPageRequest(call)
                val list = service.list(page)
                call.respond(list)
            }

            // 详情查询
            get("/{$pkProp}", {
                tags = listOf("$className")
                summary = "获取${className}详情"
                securitySchemeName = "BearerAuth"
            }) {
                val id = call.parameters["$pkProp"]?.toIntOrNull()
                    ?: return@get call.respond(KResult.fail<Any>("参数错误"))
                val entity = service.getById(id)
                call.respond(KResult.ok(entity))
            }

            // 新增
            post({
                tags = listOf("$className")
                summary = "新增$className"
                securitySchemeName = "BearerAuth"
            }) {
                val entity = call.receive<$className>()
                service.save(entity)
                call.respond(toAjax(true))
            }

            // 删除
            delete("/{$pkProp}", {
                tags = listOf("$className")
                summary = "删除$className"
                securitySchemeName = "BearerAuth"
            }) {
                val id = call.parameters["$pkProp"]?.toIntOrNull()
                    ?: return@delete call.respond(KResult.fail<Any>("参数错误"))
                service.deleteById(id)
                call.respond(toAjax(true))
            }
        }
    }
}

fun Route.${className.replaceFirstChar { it.lowercase() }}Routes() {
    ${className}Controller().apply { routes() }
}
""".trimIndent()
    }

    /**
     * 保存生成的代码到文件
     */
    fun saveToFile(code: GeneratedCode) {
        val baseDir = File(outputDir, basePackage.replace(".", "/"))
        
        // Entity
        val entityDir = File(baseDir, "framework/web/domain")
        entityDir.mkdirs()
        File(entityDir, "${code.className}.kt").writeText(code.entityCode)
        
        // Service
        val serviceDir = File(baseDir, "framework/web/service")
        serviceDir.mkdirs()
        File(serviceDir, "${code.className}Service.kt").writeText(code.serviceCode)
        
        // Controller
        val controllerDir = File(baseDir, "framework/web/controller")
        controllerDir.mkdirs()
        File(controllerDir, "${code.className}Route.kt").writeText(code.controllerCode)
    }

    /**
     * 表名转类名
     */
    private fun toClassName(tableName: String): String {
        return tableName.split("_")
            .joinToString("") { it.lowercase().replaceFirstChar { c -> c.uppercase() } }
    }
}

/**
 * 生成的代码
 */
data class GeneratedCode(
    val entityCode: String,
    val serviceCode: String,
    val controllerCode: String,
    val className: String,
    val tableName: String
)
